### ISSUE TITLE
should be using namespace::autoclean

### ISSUE THREAD

**Issue by karenetheridge** [Csson/p5-Dist-Zilla-Plugin-InsertExample-FromMojoTemplates#1]
namespace::sweep is now obsolete and namespace::autoclean handles more cases, more properly. Anything using Moose, Moo or Mouse should absolutely be using namespace::autoclean; for a few situations (e.g. exporter classes) namespace::clean might be preferable, but a ticket reporting the issue would still be very much welcomed.

(0.16 is the version that dropped the loading of Class::MOP to introspect Moo classes.)

see https://rt.cpan.org/Ticket/Display.html?id=101222

**Comment by Csson** [comment]
This is pretty much in the same situation as Csson/p5-dist-zilla-plugin-test-createfrommojotemplate#1

**Comment by Csson** [comment]
Fixed (and deprecated).
